### PR TITLE
Add script to match the pipenv with the available python version.

### PR DESCRIPTION
**Pull request by inverted-tree**
Calling `pipenv install` would not work becaue I was on a newer version of Python. The new script checks if the current Python version satisfies the requirement in the Pipfile and then auto adjusts this file and syncs the lock file. This avoids having to manually update this every time python is updated on the system.

### CODE REVIEW

**Comment by pcdi** [comment]
If we replace the `python_version` in the Pipfile with the available OS version in all cases, I think it would probably be easier to not specify it as a requirement at all (i.e. get rid of the whole `[requires]` block) or set it to `python_version = "3"`, even though that breaks `pipenv check`: `Specifier python_version does not match`.

The rationale is: If the python version can be arbitrarily switched to whatever is present on the system and it does not break the script, then probably it is not really a hard requirement (barring breaking changes in the future).
What are your thoughts on this?

**Comment by inverted-tree** [comment]
The problem is that for the script to work at least python 3.10 is required because the `match` statement was introduced only in this version:
```python
match chapter["pagination_type"]:
    case "arabic":
        pagination_style = pypdf.constants.PageLabelStyle.DECIMAL
    case "roman":
        pagination_style = pypdf.constants.PageLabelStyle.LOWERCASE_ROMAN
    case _:
        raise KeyError
```
I do not see why any newer version would break the script. Sadly one cannot specify something like
```toml
[requires]
python_version = ">=3.10"
```
which would solve the problem. Alternatively one could swap the `match` for a plain old `if` statement to reduce the required version even further. I find it just pretty impractical to specify a minor release as the exact required version.

**Comment by pcdi** [comment]
> I find it just pretty impractical to specify a minor release as the exact required version.

I wholeheartedly agree, but the necessary functionality will not exist in pipenv, I fear: https://github.com/pypa/pipenv/issues/1050 

I have to admit I am not a huge fan of adding functionality to this script that is not strictly super necessary for the proper functioning of this script (theoretically one could just install the required Python version via pyenv or the like). However, as I do think that this use case is valid, I would like to find a good solution. So what would you say are the main advantages of adding an additional script to change the Pipfile over other solutions?

Right now I am thinking that perhaps the Pipfile should just have
```
[requires]
python_version = "3"
```
(or nothing at all) and then the script itself should check with something like `if not sys.version_info >= (3, 10)` to force the user to provide a correct Python version. Because in any case, if the user does not have at least 3.10 installed, they will have to update their Python, and for anything above 3.10 it is (probably) irrelevant what exact version they are using.
Let me know what you think.

**Comment by inverted-tree** [comment]
> I have to admit I am not a huge fan of adding functionality to this script that is not strictly super necessary for the proper functioning of this script

I understand this, especially since it seems a litte "over the top" given what it provides. I have made the proposed adjustment to the [Pipfile](https://github.com/inverted-tree/cambridge_core_downloader/blob/main/Pipfile) and added a function that checks the compatibility of the installed python version:

```python
def check_python_version():
    if not sys.version_info >= (3,10):
        print("At least python version 3.10 is required to run this script. Please consider updating your python environment ({}.{})".format(sys.version_info.major, sys.version_info.minor))
        sys.exit(1)
```

Also I changed the behaviour of the file already exists check such that the program stops instead of printing a stack trace when a book has already been downloaded.

**Comment by inverted-tree** [comment]
Maybe @pcdi can take a look again and then accept / reject the pull request? Thanks!

**Review by pcdi — APPROVED** [review]

**Comment by pcdi** [comment]
@inverted-tree Thanks for making the adjustments (and for your patience)!

**Pull request merged**
